name: Docker Build

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch: 

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    name: deploy steps
    steps:
      - uses: actions/checkout@v2
      - name: install 
        run: yarn install
      - name: build
        run: yarn build-client
      - name: Build and push Docker images
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: xbeeant/yapi
          tags: latest